### ISSUE TITLE
🐛 Bug Report - Unable to authorize

### ISSUE THREAD

**Issue by L4stIdi0t** [pysnippet/fastapi-oauth2#32]
### Bug description

It throws the following error Expecting a string- or bytes-formatted key. with a 401 return

### Reproduction steps

I am trying to use the code from the example in my own setup but i always get 401

![Screenshot 2024-02-24 150329](https://github.com/pysnippet/fastapi-oauth2/assets/75753024/2d3ea7be-c608-47ba-9ca9-64b45b7f470a)
on the left my own enviroment, on the right the example from the repo

and it throws this error:
Expecting a string- or bytes-formatted key. with a 401 return

### Screenshots

![DESCRIPTION](LINK.png)

**Comment by ArtyomVancyan** [comment]
Hi @L4stIdi0t, sorry to hear about the issue, but I am unsure I understand what you are trying to do.

- Are you trying to use the token to call GitHub API?
- What package versions are installed on your environment?
- What changes did you make to the example app before getting the error message?

**Comment by L4stIdi0t** [comment]
i use domain.com/oauth/github/authorize and then let it do its thing like you would in the example

the github repo that i invited you contains all files which interact with oauth2-fastapi and my requirements.txt from pip freeze

i have never gotten it to work, i tried porting it from the example to mine, but i do not see where i messed up, i believe the token shouldnt give a 401 because of jwt_create erroring

i tried reinstalling it with a clean venv and only using oauth2, uvicorn and sqlalchemy

https://github.com/L4stIdi0t/debug_oauth/tree/main

**Comment by ArtyomVancyan** [comment]
Could you please also commit the models and database so I can run and debug them?

**Comment by L4stIdi0t** [comment]
Added them

**Comment by ArtyomVancyan** [comment]
Okay, I had to flatten the files and comment on some database-related stuff to be able to run the app. However, the `jwt_create` is used to create your JWT with your desired payload. I am not sure exactly what step the 401 status code threw. Please try to run the https://github.com/pysnippet/fastapi-oauth2/tree/master/examples/demonstration without making any code changes. If it runs without any issues, then the problem is in your implementation; otherwise, it is a problem with the library (less possible, because I just tested it and did not get any errors). What I am guessing is that you tried to create a token using the `jwt_create` and call a GitHub API which could result in 401. If you want to use your access token after user authentication, you can get it from the request context (see the [docs](https://docs.pysnippet.org/fastapi-oauth2/references/tutorials#access-token)).

**Comment by L4stIdi0t** [comment]
Thank you for your time and sorry for wasting it @ArtyomVancyan. I had a small typo in my .env file and that is why it did not work
